-- public.adp_deficiencia_fisica_idoso definition

-- Drop table

-- DROP TABLE public.adp_deficiencia_fisica_idoso;

CREATE TABLE public.adp_deficiencia_fisica_idoso (
	id int4 NOT NULL GENERATED ALWAYS AS IDENTITY,
	descricao varchar NOT NULL
);


-- public.equipamento definition

-- Drop table

-- DROP TABLE public.equipamento;

CREATE TABLE public.equipamento (
	id int4 NOT NULL GENERATED ALWAYS AS IDENTITY,
	descricao varchar NOT NULL
);


-- public.estrutura_fisica_ambiencia definition

-- Drop table

-- DROP TABLE public.estrutura_fisica_ambiencia;

CREATE TABLE public.estrutura_fisica_ambiencia (
	id int4 NOT NULL GENERATED ALWAYS AS IDENTITY,
	descricao varchar NOT NULL
);


-- public.medicamento definition

-- Drop table

-- DROP TABLE public.medicamento;

CREATE TABLE public.medicamento (
	id int4 NOT NULL GENERATED ALWAYS AS IDENTITY,
	descricao varchar NOT NULL
);


-- public.municipio definition

-- Drop table

-- DROP TABLE public.municipio;

CREATE TABLE public.municipio (
	id int8 NOT NULL,
	geom public.geometry(multipolygon, 4326) NULL,
	"_uid_" numeric NULL,
	geocod varchar(254) NULL,
	"name" varchar(60) NULL,
	state varchar(2) NULL,
	CONSTRAINT municipio_corr_pkey PRIMARY KEY (id)
);
CREATE INDEX sidx_municipio_corr_geom ON public.municipio USING gist (geom);


-- public.ubs definition

-- Drop table

-- DROP TABLE public.ubs;

CREATE TABLE public.ubs (
	vlr_latitude float4 NULL,
	vlr_longitude float4 NULL,
	cod_munic int4 NULL,
	cod_cnes int4 NULL,
	nom_estab varchar NULL,
	dsc_endereco varchar NULL,
	dsc_bairro varchar NULL,
	dsc_cidade varchar NULL,
	dsc_telefone varchar NULL,
	estr_fis_id int4 NULL,
	adp_def_idoso_id int4 NULL,
	equipamento_id int4 NULL,
	medicamento_id int4 NULL,
	geom public.geometry(point, 4326) NULL,
	municipio_id int4 NULL,
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	uf varchar(2) NULL,
	CONSTRAINT ubs_pk PRIMARY KEY (id)
);


-- public.ubs_csv definition

-- Drop table

-- DROP TABLE public.ubs_csv;

CREATE TABLE public.ubs_csv (
	vlr_latitude float4 NULL,
	vlr_longitude float4 NULL,
	cod_munic int4 NULL,
	cod_cnes int4 NULL,
	nom_estab varchar NULL,
	dsc_endereco varchar NULL,
	dsc_bairro varchar NULL,
	dsc_cidade varchar NULL,
	dsc_telefone varchar NULL,
	dsc_estrut_fisic_ambiencia varchar NULL,
	dsc_adap_defic_fisic_idosos varchar NULL,
	dsc_equipamentos varchar NULL,
	dsc_medicamentos varchar NULL,
	estr_fis_id int4 NULL,
	adp_def_idosos_id int4 NULL,
	equipamentos_id int4 NULL,
	medicamentos_id int4 NULL
);